[package]
name = "bitcoin_wasm_bech32"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.11.0"
bs58 = "0.5.1"
hex = "0.4.3"
ripemd = "0.1.3"
sha2 = "0.10.8"
wasm-bindgen = "0.2.95"

[lib]
crate-type = ["cdylib"]
